### ISSUE TITLE
configure: error: Could not link against boost_iostreams !

### ISSUE THREAD

**Issue by lyhistory** [libbitcoin/libbitcoin-system#1100]
Error
 ./configure:
checking whether the Boost::IOStreams library is available... yes
checking for exit in -lboost_iostreams... no
configure: error: Could not link against boost_iostreams !

SourceCode: master branch

ENV: running ubuntu 18.04.1 on virtualbox

![libbitcoin](https://user-images.githubusercontent.com/1522513/51017577-77825100-15af-11e9-9203-a44351132778.png)

**Comment by thecodefactory** [comment]
Debian/Ubuntu instructions are here: https://github.com/libbitcoin/libbitcoin-system/blob/master/README.md#debianubuntu

See: `$ ./install.sh --prefix=/home/me/myprefix --build-boost --disable-shared`

Can you confirm this is what you're running?

**Comment by lyhistory** [comment]
no, I use the advanced way:
./autogen.sh
./configure

**Comment by thecodefactory** [comment]
I would try to not do this for now.  If you are advanced and already know what you're doing, you probably know why the boost library can't be found and can double check your pkg-config environment for the proper dependencies, etc.  Otherwise, I recommend always using the install script until you have a better feel for how it works and what's needed, etc.

**Comment by lyhistory** [comment]
ok, thanks for your advise

**Comment by thecodefactory** [comment]
Any luck getting the build going?

**Comment by lyhistory** [comment]
@thecodefactory hi, I took your suggestion and install with https://raw.githubusercontent.com/libbitcoin/libbitcoin-explorer/version3/install.sh, it works

**Comment by thecodefactory** [comment]
Great, glad to hear!
