### ISSUE TITLE
configure: error: Boost 1.72.0 or later is required but was not found.

### ISSUE THREAD

**Issue by st4rgut24** [libbitcoin/libbitcoin-system#1277]
I am trying to build libbitcoin-system with boost version 1.67.0 due to issues I was running into with newer versions of boost. However, when I run `install.sh` with libbitcoin-system v3.6.0 I get the following error. I checked the install script and it seems it predates boost 1.72.0 (1.62.0) so I'm not sure why I'm required to use 1.72.0. Is there an earlier branch where I would be able to successfully build with boost 1.67.0?

My OS is Ubuntu 22.04 amd 64 bit
```
checking for boostlib >= 1.72.0 (107200)... configure: We could not detect the boost libraries (version 1.72.0 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: Boost 1.72.0 or later is required but was not found.
```

**Comment by pmienk** [comment]
I am currently working to update the `README.md`.

At present, the `version3` branch requires `boost 1.72.0`. This change was adopted due to cross platform concerns approximately eleven months ago. It should be noted that there is a break introduced by `boost 1.77.0` which is unguarded for within the configuration script.

I would advise you to execute the `install.sh` script providing it the means to `--build-boost` along with specifying a `--prefix` path for installation. In this way you can isolate the version of boost required by `libbitcoin-system` from the libraries in your general environment.

Of course, you're free to look through the history of changes and revert to a point where `configure.ac` properly guarded for a boost version to your liking. I would not advise this, as it would be unlikely you'd find further assistance.
