### ISSUE TITLE
sudo ./install.sh (Ubuntu 22.04LTS)

### ISSUE THREAD

**Issue by dedetuga** [libbitcoin/libbitcoin-system#1366]
Hi,
when i try to compile this repo i get allways the error:

`In file included from ./include/bitcoin/system.hpp:63,
                 from examples/main.cpp:21:
./include/bitcoin/system/log/file_collector.hpp:71:15: error: ‘uintmax_t libbitcoin::log::file_collector::scan_for_files(boost::log::v2_mt_posix::sinks::file::scan_method, const boost::filesystem::path&, unsigned int*)’ marked ‘override’, but does not override
   71 |     uintmax_t scan_for_files(boost::log::sinks::file::scan_method method,
      |               ^~~~~~~~~~~~~~
make: *** [Makefile:4239: examples/libbitcoin_system_examples-main.o] Erro 1`

there is a way to correct it?

thanks

**Comment by pmienk** [comment]
More information would be helpful.  In absence of any, I would speculate that this is due to a breaking change in a newer version of boost which is not backwards compatible.

I would suggest a twofold approach of isolating installation to a prefix directory and also allowing the installation script to install the minimum required version of boost to that prefix.

**Comment by evoskuil** [comment]
I think your right, and that we may have encountered this in v4.
