### ISSUE TITLE
Ubuntu: build failure

### ISSUE THREAD

**Issue by Ahmet1s2** [libbitcoin/libbitcoin-system#1512]
errors.log:

In file included from /home/shit/libbitcoin-system/src/log/file_collector.cpp:18:
/home/shit/libbitcoin-system/builds/cmake/../../include/bitcoin/system/log/file_collector.hpp:71:15: error: ‘uintmax_t libbitcoin::log::file_collector::scan_for_files(boost::log::v2s_mt_posix::sinks::file::scan_method, const boost::filesystem::path&, unsigned int*)’ marked ‘override’, but does not override
   71 |     uintmax_t scan_for_files(boost::log::sinks::file::scan_method method,
      |               ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/bitcoin-system.dir/build.make:552: CMakeFiles/bitcoin-system.dir/home/shit/libbitcoin-system/src/log/file_collector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/bitcoin-system.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by pmienk** [comment]
Additional details like the command executed and full output make diagnosing these things much easier.

My guess is that you've either not prefixed your installation and/or not allowed the installation script to build boost and are now dealing with a version clash whereby our `version3` branch expects a version of boost that is bounded by version numbers due to a breaking change. While this is ideally detected by configuration, boost detection m4s don't allow for specification of an upper bound allowing for this error. The upper bound is appropriately documented on the `version3` branch README and is installed via the installation script.

Please provide additional details if the above is not what you are encountering, closing this issue until additional information is provided.

**Comment by Ahmet1s2** [comment]
it worked thanks
