### ISSUE TITLE
ec_keys.cpp fails to build

### ISSUE THREAD

**Issue by paulhandy** [libbitcoin/libbitcoin-system#164]
Failed to build. Here's the output error:

```
src/math/ec_keys.cpp: In function ‘libbitcoin::endorsement libbitcoin::sign(libbitcoin::ec_secret, libbitcoin::hash_digest, libbitcoin::ec_secret)’:
src/math/ec_keys.cpp:145:57: error: invalid conversion from ‘std::array<unsigned char, 32ul>::size_type {aka long unsigned int}’ to ‘unsigned char*’ [-fpermissive]
if (0 < secp256k1_ecdsa_sign(hash.data(), hash.size(), signature.data(),
^
src/math/ec_keys.cpp:146:47: error: cannot convert ‘unsigned char*’ to ‘int*’ for argument ‘3’ to ‘int secp256k1_ecdsa_sign(const unsigned char*, unsigned char*, int*, const unsigned char*, const unsigned char*)’
&out_size, secret.data(), nonce.data()))
^
src/math/ec_keys.cpp: In function ‘libbitcoin::compact_signature libbitcoin::sign_compact(libbitcoin::ec_secret, libbitcoin::hash_digest, libbitcoin::ec_secret)’:
src/math/ec_keys.cpp:162:65: error: invalid conversion from ‘std::array<unsigned char, 32ul>::size_type {aka long unsigned int}’ to ‘unsigned char*’ [-fpermissive]
if (0 < secp256k1_ecdsa_sign_compact(hash.data(), hash.size(),
^
src/math/ec_keys.cpp:163:70: error: cannot convert ‘std::array<unsigned char, 32ul>::pointer {aka unsigned char*}’ to ‘int*’ for argument ‘5’ to ‘int secp256k1_ecdsa_sign_compact(const unsigned char*, unsigned char*, const unsigned char*, const unsigned char*, int*)’
out.signature.data(), secret.data(), nonce.data(), &out.recid))
^
src/math/ec_keys.cpp: In function ‘bool libbitcoin::verify_signature(const ec_point&, libbitcoin::hash_digest, const endorsement&)’:
src/math/ec_keys.cpp:176:63: error: invalid conversion from ‘std::array<unsigned char, 32ul>::size_type {aka long unsigned int}’ to ‘const unsigned char*’ [-fpermissive]
return 1 == secp256k1_ecdsa_verify(hash.data(), hash.size(),
^
src/math/ec_keys.cpp:177:24: error: invalid conversion from ‘const unsigned char*’ to ‘int’ [-fpermissive]
signature.data(), signature.size(), public_key.data(),
^
src/math/ec_keys.cpp:177:42: error: invalid conversion from ‘std::vector<unsigned char>::size_type {aka long unsigned int}’ to ‘const unsigned char*’ [-fpermissive]
signature.data(), signature.size(), public_key.data(),
^
src/math/ec_keys.cpp:177:61: error: invalid conversion from ‘const unsigned char*’ to ‘int’ [-fpermissive]
signature.data(), signature.size(), public_key.data(),
^
src/math/ec_keys.cpp:179:5: error: too many arguments to function ‘int secp256k1_ecdsa_verify(const unsigned char*, const unsigned char*, int, const unsigned char*, int)’
);
^
In file included from src/math/ec_keys.cpp:23:0:
/usr/include/secp256k1.h:72:34: note: declared here
SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdsa_verify(
^
src/math/ec_keys.cpp: In function ‘libbitcoin::ec_point libbitcoin::recover_compact(libbitcoin::compact_signature, libbitcoin::hash_digest, bool)’:
src/math/ec_keys.cpp:193:68: error: invalid conversion from ‘std::array<unsigned char, 32ul>::size_type {aka long unsigned int}’ to ‘const unsigned char*’ [-fpermissive]
if (0 < secp256k1_ecdsa_recover_compact(hash.data(), hash.size(),
^
src/math/ec_keys.cpp:195:24: error: cannot convert ‘unsigned char*’ to ‘int*’ for argument ‘4’ to ‘int secp256k1_ecdsa_recover_compact(const unsigned char*, const unsigned char*, unsigned char*, int*, int, int)’
signature.recid))
^
Makefile:1431: recipe for target 'src/math/src_libbitcoin_la-ec_keys.lo' failed
make: *** [src/math/src_libbitcoin_la-ec_keys.lo] Error 1
```

**Comment by skaht** [comment]
I made the same bonehead mistake of using bitcoin/secp256k1 instead of libbitcoin/secp256k1 using OSX Yosemite.  Slowly making headway getting SX to compile.  Here are my compilation notes so far.

A) Building libsecp256k1

   From: https://github.com/libbitcoin/secp256k1
   DO NOT USE!!!: https://github.com/bitcoin/secp256k1 with https://github.com/bitcoin/secp256k1.git configuration
   Dependencies: none_transpired

   1) cd ~/Projects
   2) mkdir -p libsecp256k1 && cd libsecp256k1
   3) git clone https://github.com/libbitcoin/secp256k1.git
   4) tar cvzf secp256k1.tar.gz secp256k1
   5) cd secp256k1
   6) ./autogen.sh
   7) cd .. && mkdir -p src && cd src
   8) ../secp256k1/configure —-help
   9) ../secp256k1/configure --prefix=$HOME/Projects/libsecp256k1
   10) make
   11) make install

B) Building LibBitcoin

   From: https://github.com/libbitcoin/libbitcoin
   Dependencies: boost, gmp, gcc48, libsecp256k1  ( used “brew” to install boost, gmp, gcc48; and rolled my own libsecp256k1 package )

   1) cd ~/Projects
   2) mkdir -p LibBitcoin && cd LibBitcoin
   3) git clone https://github.com/libbitcoin/libbitcoin.git
   4) tar cvzf libbitcoin.tar.gz libbitcoin
   5) cd libbitcoin
   6) git tag
   7) git checkout v2.7.0
   8) autoreconf -iv
   9) cd .. && mkdir -p src && cd src
   10) ../libbitcoin/configure --help
   11) setenv CC  /usr/local/bin/gcc-4.8
   12) setenv CXX /usr/local/bin/g++-4.8
   13) ../libbitcoin/configure PKG_CONFIG_PATH=$HOME/Projects/libsecp256k1/lib/pkgconfig --prefix=$HOME/Projects/LibBitcoin -enable-ndebug --disable-dependency-tracking
   14) make
   15) make install

C) Building SX

   From: https://github.com/spesmilo/sx
   Dependencies: libbitcoin, libsecp256k1, libwallet  ( rolled my own libbitcoin, libsecp256k1 packages; libwallet is a WIP )

   1) cd ~/Projects
   2) mkdir SX && cd SX
   3) git clone https://github.com/spesmilo/sx.git
   4) tar cvzf sx.tar.gz sx
   5) cd sx
   6) git tag
   7) git checkout v1.0
   8) autoreconf -iv
   9) cd .. && mkdir -p src && cd src
   10) ../sx/configure --help
   11) setenv CC  /usr/local/bin/gcc-4.8
   12) setenv CXX /usr/local/bin/g++-4.8
   13) ../sx/configure PKG_CONFIG_PATH=$HOME/Projects/LibBitcoin/lib/pkgconfig:$HOME/Projects/libsecp256k1/lib/pkgconfig --prefix=$HOME/Projects/SX --sysconfdir=$HOME/Projects/SX/etc --disable-dependency-tracking
   14) make
   15) make install

**Comment by evoskuil** [comment]
@skaht This issue has been moved to the SX repository.

**Comment by skaht** [comment]
I'm on the last leg for getting BX to compile on Yosemite. You were right SX was an early first generation hack that has a dependency on Python code. It took a while playing detective over the weekend to sort things out to compile BX from sources. I have src_libbitcoin_explorer_la-base58-encode.lo compiling now.

**Comment by evoskuil** [comment]
All you need to do to compile bx from sources is to download and run the `install.sh`. See instructions here: https://github.com/libbitcoin/libbitcoin-explorer/blob/master/README.md#macintosh

**Comment by skaht** [comment]
Those compilation notes are generalities to keep us after hour hackers in the ballpark... It took me considerable detective work and about 100 lines of detailed commands to download the proper source, get everything  (i.e., libbitcoin-explorer, libbitcoin-client, libczmq++, libczmq, libzmq, libsodium, libbitcoin, and libsecp256k1) to configure, compile and link together. My notes are captures in a file. Don't get me wrong, BX will be a really good set of tools to experiment with and learn from:-) My hat is off for those that labored to build this body of work.
